# Uncomment this line to define a global platform for your project
platform :ios, '8.3'

target 'FlickrScroller' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlickrScroller

  target 'FlickrScrollerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlickrScrollerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
